name: Atl Generic Repository - Deploy

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build
      run: dotnet build --configuration Debug
      working-directory: ./src

    - name: Run unit tests
      run: dotnet test --configuration Debug
      working-directory: ./src

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Generate nuget package
      run: dotnet pack --configuration Release
      working-directory: ./src
